# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(331, 170)
        AuthWindow.setMinimumSize(QtCore.QSize(0, 0))
        AuthWindow.setMaximumSize(QtCore.QSize(334, 222))
        self.centralWidget = QtWidgets.QWidget(AuthWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.user_password = QtWidgets.QLineEdit(self.centralWidget)
        self.user_password.setGeometry(QtCore.QRect(10, 70, 311, 31))
        self.user_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password.setObjectName("user_password")
        self.user_login = QtWidgets.QLineEdit(self.centralWidget)
        self.user_login.setGeometry(QtCore.QRect(10, 20, 311, 31))
        self.user_login.setObjectName("user_login")
        self.login_button = QtWidgets.QPushButton(self.centralWidget)
        self.login_button.setGeometry(QtCore.QRect(70, 120, 191, 31))
        self.login_button.setObjectName("login_button")
        AuthWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "MainWindow"))
        self.user_password.setPlaceholderText(_translate("AuthWindow", "Пароль"))
        self.user_login.setPlaceholderText(_translate("AuthWindow", "Логин"))
        self.login_button.setText(_translate("AuthWindow", "Войти"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    AuthWindow = QtWidgets.QMainWindow()
    ui = Ui_AuthWindow()
    ui.setupUi(AuthWindow)
    AuthWindow.show()
    sys.exit(app.exec_())
